### PR TITLE
Updated menu_nav & menu_com to show decimal point on iOS

### PR DESCRIPTION
**Pull request by fitzroymckay**
I updated menu_nav and menu_com to show decimal point on iPhone when in direct input mode

The input mode just needed to be switched from numeric to decimal. I suppose it will work on Android too, but I cannot test.

### CODE REVIEW

**Comment by mracko** [comment]
Thanks for finding this bug. I don't have an iOS device so I haven't noticed it myself. I'll test this on my Android devices and will let you if everything is OK.

**Comment by mracko** [comment]
I've finally managed to have a look at it and you're right - the keyboard on the iOS didn't show the decimal button. I've missed it because it was never an issue on my Android tablet.

However, your fix doesn't fully solve the issue. When you have a "European" iOS, the keyboard will show a comma instead of a dot. Unfortunately, the app doesn't recognize a comma as a decimal separator so you still can't type in a decimal frequency. A simple solution would be to add a JavaScript function that replaces commas with dots. Do you think you could do it? Otherwise I'll have a look at it, hopefully, next week.

Thanks a lot!

**Comment by fitzroymckay** [comment]
I have added a lang="en-US" field in the frequency input box, I believe that should fix it. It shows a dot on my iOS even though I have switched to a french keyboard only.

I have also corrected inputmode to decimal for ADF, I had forgotten it last time

**Comment by mracko** [comment]
I've merged your commit into the master branch. Thanks a lot for your fix! I've made two additions/changes to the code:
- Added a little JS which replaces "," with ".". This is just for compatibility reasons because the lang="en-US" may not work on all browsers or keyboards. The JS makes it more robust.
- Changed the ADF back to numeric because ADF doesn't use decimals.

**Comment by fitzroymckay** [comment]
Thank you!

**Pull request merged**
